name: push repository
on: 
  push:
    branches-ignore:
      - master
      - develop

jobs: 
  push_workflow:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2 
 
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8  

        # Cache Python dependencies
        - name: Cache Python dependencies
          uses: actions/cache@v2
          with:
            path: ~/.cache/pip  # The path to your pip cache directory
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  
        - name: Install dependencies
          run: |
            pip install -r requirements.txt 
            cd fastapi/ 

        - name: Run Pylint and fail if rating is less than 6/10
          run: |
            pylint --fail-under=6 --recursive=y --enable=W $(find . -type f -name "*.py")

        - name: Run pytest
          run: pytest  

        # - name: Build and push Docker image
        #   uses: docker/build-push-action@v2
        #   with:
        #     context: .  # Path to the directory containing your Dockerfile (the current directory in this case)
        #     push: false  # Set to 'false' if you only want to build the image and not push it
        #testinggg

        